<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="medical_wheelchair">

  <!-- Materials -->
  <material name="silver"><color rgba="0.75 0.75 0.75 1"/></material>
  <material name="dark_grey"><color rgba="0.2 0.2 0.2 1"/></material>
  <material name="fabric_red"><color rgba="0.6 0.1 0.1 1"/></material>
  <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
  <material name="grey"><color rgba="0.5 0.5 0.5 1"/></material>

  <!-- Inertia Macros -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m}"/>
      <inertia ixx="${(m/12)*(h*h + d*d)}" ixy="0" ixz="0" iyy="${(m/12)*(w*w + d*d)}" iyz="0" izz="${(m/12)*(w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m}"/>
      <inertia ixx="${(m/12)*(3*r*r + h*h)}" ixy="0" ixz="0" iyy="${(m/12)*(3*r*r + h*h)}" iyz="0" izz="${(m/2)*r*r}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="tubular_link" params="name length radius m material">
    <link name="${name}">
      <xacro:cylinder_inertia m="${m}" r="${radius}" h="${length}"/>
      <visual>
        <origin xyz="${length/2} 0 0" rpy="0 1.5708 0"/>
        <geometry><cylinder radius="${radius}" length="${length}"/></geometry>
        <material name="${material}"/>
      </visual>
      <collision>
        <origin xyz="${length/2} 0 0" rpy="0 1.5708 0"/>
        <geometry><cylinder radius="${radius}" length="${length}"/></geometry>
      </collision>
    </link>
  </xacro:macro>

  <!-- Base Footprint: No inertia for root link -->
  <link name="base_footprint">
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0.35" rpy="0 0 0"/>
  </joint>

  <!-- Base Link (Seat) -->
  <link name="base_link">
    <xacro:box_inertia m="5.0" w="0.45" h="0.45" d="0.05"/>
    <visual>
      <geometry><box size="0.45 0.45 0.05"/></geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <geometry><box size="0.45 0.45 0.05"/></geometry>
    </collision>
  </link>

  <!-- Backrest -->
  <link name="backrest">
    <xacro:box_inertia m="2.0" w="0.05" h="0.45" d="0.5"/>
    <visual>
      <geometry><box size="0.05 0.45 0.5"/></geometry>
      <material name="fabric_red"/>
    </visual>
    <collision>
      <geometry><box size="0.05 0.45 0.5"/></geometry>
    </collision>
  </link>
  <joint name="backrest_joint" type="fixed">
    <parent link="base_link"/>
    <child link="backrest"/>
    <origin xyz="-0.2 0 0.275" rpy="0 0 0"/>
  </joint>

  <!-- Armrests -->
  <link name="left_armrest">
    <xacro:box_inertia m="1.0" w="0.4" h="0.04" d="0.2"/>
    <visual><geometry><box size="0.4 0.04 0.2"/></geometry><material name="silver"/></visual>
    <collision><geometry><box size="0.4 0.04 0.2"/></geometry></collision>
  </link>
  <joint name="left_armrest_joint" type="fixed">
    <parent link="base_link"/>
    <child link="left_armrest"/>
    <origin xyz="0 0.2 0.125" rpy="0 0 0"/>
  </joint>

  <link name="right_armrest">
    <xacro:box_inertia m="1.0" w="0.4" h="0.04" d="0.2"/>
    <visual><geometry><box size="0.4 0.04 0.2"/></geometry><material name="silver"/></visual>
    <collision><geometry><box size="0.4 0.04 0.2"/></geometry></collision>
  </link>
  <joint name="right_armrest_joint" type="fixed">
    <parent link="base_link"/>
    <child link="right_armrest"/>
    <origin xyz="0 -0.2 0.125" rpy="0 0 0"/>
  </joint>

  <!-- Main Chassis Hub -->
  <link name="chassis_hub">
    <xacro:box_inertia m="2.0" w="0.2" h="0.3" d="0.05"/>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="0.2 0.3 0.05"/></geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="0.2 0.3 0.05"/></geometry>
    </collision>
  </link>
  <joint name="chassis_hub_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_hub"/>
    <origin xyz="0 0 -0.05" rpy="0 0 0"/>
  </joint>

  <!-- Navigation Macros for Sides -->
  <xacro:macro name="chassis_side" params="side reflect">
    <!-- Rear Sloped Arm -->
    <xacro:tubular_link name="rear_arm_${side}" length="0.25" radius="0.02" m="0.5" material="silver"/>
    <joint name="rear_arm_${side}_joint" type="fixed">
      <parent link="chassis_hub"/>
      <child link="rear_arm_${side}"/>
      <!--change-->
      <origin xyz="-0.1 ${reflect * 0.15} 0" rpy="0 1.2 3.14159"/>
    </joint>

    <!-- Rear Wheel -->
    <link name="rear_${side}_wheel">
      <xacro:cylinder_inertia m="0.8" r="0.07" h="0.05"/>
      <visual>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="0.07" length="0.05"/></geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="0.07" length="0.05"/></geometry>
      </collision>
      <gazebo reference="rear_${side}_wheel">
        <mu1>1.0</mu1>
        <mu2>1.0</mu2>
        <self_collide>false</self_collide>
      </gazebo>
    </link>
    <joint name="rear_${side}_wheel_joint" type="continuous">
      <parent link="rear_arm_${side}"/>
      <child link="rear_${side}_wheel"/>
      <origin xyz="0.25 0 0" rpy="0 -1.2 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <!-- Front Sloped Arm -->
    <xacro:tubular_link name="front_arm_${side}" length="0.15" radius="0.02" m="0.3" material="silver"/>
    <joint name="front_arm_${side}_joint" type="fixed">
      <parent link="chassis_hub"/>
      <child link="front_arm_${side}"/>
      <origin xyz="0.1 ${reflect * 0.15} 0" rpy="0 0.8 0"/>
    </joint>

    <!-- Bogie Pivot -->
    <link name="bogie_pivot_${side}">
      <xacro:cylinder_inertia m="0.1" r="0.015" h="0.05"/>
      <visual>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="0.015" length="0.05"/></geometry>
        <material name="grey"/>
      </visual>
    </link>
    <joint name="bogie_pivot_${side}_joint" type="fixed">
      <parent link="front_arm_${side}"/>
      <child link="bogie_pivot_${side}"/>
      <origin xyz="0.15 0 0" rpy="0 0 0"/>
    </joint>

    <!-- Inverted V Bogie branches -->
    <!-- Middle branch -->
    <xacro:tubular_link name="bogie_middle_arm_${side}" length="0.15" radius="0.015" m="0.2" material="silver"/>
    <joint name="bogie_middle_arm_joint_${side}" type="fixed">
      <parent link="bogie_pivot_${side}"/>
      <child link="bogie_middle_arm_${side}"/>
      <!--change-->
      <origin xyz="0 0 0" rpy="0 1.38 0"/> 
      <axis xyz="0 1 0"/>
      <limit effort="10" velocity="1" lower="-3.14" upper="3.14"/>
    </joint>

    <!-- Front branch -->
    <xacro:tubular_link name="bogie_front_arm_${side}" length="0.15" radius="0.015" m="0.2" material="silver"/>
    <joint name="bogie_front_arm_joint_${side}" type="fixed">
      <parent link="bogie_pivot_${side}"/>
      <child link="bogie_front_arm_${side}"/>
      <!--change-->
      <origin xyz="0 0 0" rpy="0 0.16 0"/> 
      <axis xyz="0 1 0"/>
      <limit effort="10" velocity="1" lower="-3.14" upper="3.14"/>
    </joint>

    <!-- Front Wheel -->
    <link name="front_${side}_wheel">
      <xacro:cylinder_inertia m="0.5" r="0.07" h="0.05"/>
      <visual>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="0.07" length="0.05"/></geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="0.07" length="0.05"/></geometry>
      </collision>
      <gazebo reference="front_${side}_wheel">
        <mu1>0.1</mu1>
        <mu2>0.1</mu2>
        <self_collide>false</self_collide>
      </gazebo>
    </link>
    <joint name="front_${side}_wheel_joint" type="continuous">
      <parent link="bogie_front_arm_${side}"/>
      <child link="front_${side}_wheel"/>
      <!--change-->
      <origin xyz="0.15 0 0" rpy="0 -0.16 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <!-- Middle Wheel -->
    <link name="middle_${side}_wheel">
      <xacro:cylinder_inertia m="0.5" r="0.07" h="0.05"/>
      <visual>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="0.07" length="0.05"/></geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="0.07" length="0.05"/></geometry>
      </collision>
      <gazebo reference="front_${side}_wheel">
        <mu1>0.1</mu1>
        <mu2>0.1</mu2>
        <self_collide>false</self_collide>
      </gazebo>
    </link>
    <joint name="middle_${side}_wheel_joint" type="continuous">
      <parent link="bogie_middle_arm_${side}"/>
      <child link="middle_${side}_wheel"/>
      <!--change-->
      <origin xyz="0.15 0 0" rpy="0 -1.38 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:chassis_side side="left" reflect="1"/>
  <xacro:chassis_side side="right" reflect="-1"/>

  <!-- Gazebo Plugins -->
  <gazebo>
    <plugin
      filename="gz-sim-diff-drive-system"
      name="gz::sim::systems::DiffDrive">
      <left_joint>rear_left_wheel_joint</left_joint>
      <left_joint>middle_left_wheel_joint</left_joint>
      <left_joint>front_left_wheel_joint</left_joint>
      <right_joint>rear_right_wheel_joint</right_joint>
      <right_joint>middle_right_wheel_joint</right_joint>
      <right_joint>front_right_wheel_joint</right_joint>
      <wheel_separation>0.35</wheel_separation>
      <wheel_radius>0.07</wheel_radius>
      <topic>/cmd_vel</topic>
    </plugin>
  </gazebo>

  <!-- Lidar Sensor -->
  <link name="laser_frame">
    <xacro:cylinder_inertia m="0.2" r="0.05" h="0.05"/>
    <visual>
      <geometry><cylinder radius="0.05" length="0.05"/></geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser_frame"/>
    <origin xyz="0.2 0 0.1" rpy="0 0 0"/>
  </joint>

  <gazebo reference="laser_frame">
    <sensor name="gpu_lidar" type="gpu_lidar">
      <topic>scan</topic>
      <update_rate>10</update_rate>
      <lidar>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.08</min>
          <max>8.0</max>
          <resolution>0.01</resolution>
        </range>
      </lidar>
      <always_on>1</always_on>
      <visualize>true</visualize>
    </sensor>
  </gazebo>

</robot>
